//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSM.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel.DataAnnotations;

    public partial class Dict
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "代码类型名必填！")]
        public string TypeName { get; set; }
        [Required(ErrorMessage = "代码名必填！")]
        [StringLength(20,ErrorMessage ="代码名过长，不能超过20个字符！")]
        public string Name { get; set; }
        [Required(ErrorMessage = "代码值必填！")]
        [StringLength(20, ErrorMessage = "代码值过长，不能超过20个字符！")]
        public string Value { get; set; }
        [Display(Name="顺序")]
        [Required(ErrorMessage = "顺序必填！")]
        [Range(0,10)]
        public int Sort { get; set; }
    }
}
