//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public int ID { get; set; }
        public int Student_ID { get; set; }
        public int Post_ID { get; set; }
        public string Reason { get; set; }
        public string Staffroom { get; set; }
        public string Obtain { get; set; }
        public string Desc { get; set; }
        public string Statu { get; set; }
        public string Result { get; set; }
        public string Flow { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Student Student { get; set; }
    }
}
