//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Interview = new HashSet<Interview>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string LoginName { get; set; }
        public string LoginPwd { get; set; }
        public bool Sex { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Height { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Photo { get; set; }
        public string Salary { get; set; }
        public string City { get; set; }
        public string Post { get; set; }
        public string Evaluation { get; set; }
        public string Resume { get; set; }
        public string Statu { get; set; }
        public int Grade_ID { get; set; }
    
        public virtual Grade Grade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interview> Interview { get; set; }
    }
}
